version: "3"

services:
    minio:
        container_name: hl-minio-storage
        image: docker.io/bitnami/minio:2023
        environment:
            CONSOLE_SECURE_TLS_REDIRECT: "off"
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
            MINIO_SERVER_URL: https://minio.alemax.site
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - miniodata:/data
    nginx:
        container_name: hl-nginx-proxy-server
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/log.conf:/etc/nginx/log.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d/:/etc/nginx/conf.d/
            - /etc/letsencrypt/live/alemax.site/fullchain.pem:/etc/nginx/fullchain.pem
            - /etc/letsencrypt/live/alemax.site/privkey.pem:/etc/nginx/privkey.pem

volumes:
    miniodata:
