version: "3"

services:
    photoprism:
        container_name: hl-photoprism
        image: photoprism/photoprism:latest
        depends_on:
            - mariadb
        restart: unless-stopped
        security_opt:
            - seccomp:unconfined
            - apparmor:unconfined
        ports:
            - "2342:2342"
        environment:
            PHOTOPRISM_ADMIN_USER: ${MINIO_ROOT_USER}
            PHOTOPRISM_ADMIN_PASSWORD: ${MINIO_ROOT_PASSWORD}
            PHOTOPRISM_AUTH_MODE: "password" # authentication mode (public, password)
            PHOTOPRISM_SITE_URL: "https://photoprism.alemax.site/" # server URL in the format "http(s)://domain.name(:port)/(path)"
            PHOTOPRISM_ORIGINALS_LIMIT: 5000 # file size limit for originals in MB (increase for high-res video)
            PHOTOPRISM_HTTP_COMPRESSION: "gzip" # improves transfer speed and bandwidth utilization (none or gzip)
            PHOTOPRISM_LOG_LEVEL: "info" # log level: trace, debug, info, warning, error, fatal, or panic
            PHOTOPRISM_READONLY: "false" # do not modify originals directory (reduced functionality)
            PHOTOPRISM_EXPERIMENTAL: "false" # enables experimental features
            PHOTOPRISM_DISABLE_CHOWN: "false" # disables updating storage permissions via chmod and chown on startup
            PHOTOPRISM_DISABLE_WEBDAV: "false" # disables built-in WebDAV server
            PHOTOPRISM_DISABLE_SETTINGS: "false" # disables settings UI and API
            PHOTOPRISM_DISABLE_TENSORFLOW: "false" # disables all features depending on TensorFlow
            PHOTOPRISM_DISABLE_FACES: "false" # disables face detection and recognition (requires TensorFlow)
            PHOTOPRISM_DISABLE_CLASSIFICATION: "false" # disables image classification (requires TensorFlow)
            PHOTOPRISM_DISABLE_RAW: "false" # disables indexing and conversion of RAW files
            PHOTOPRISM_RAW_PRESETS: "false" # enables applying user presets when converting RAW files (reduces performance)
            PHOTOPRISM_JPEG_QUALITY: 85 # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
            PHOTOPRISM_DETECT_NSFW: "false" # automatically flags photos as private that MAY be offensive (requires TensorFlow)
            PHOTOPRISM_UPLOAD_NSFW: "true" # allows uploads that MAY be offensive (no effect without TensorFlow)
            PHOTOPRISM_DATABASE_DRIVER: "mysql" # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
            PHOTOPRISM_DATABASE_SERVER: "mariadb:3306" # MariaDB or MySQL database server (hostname:port)
            PHOTOPRISM_DATABASE_NAME: "photoprism" # MariaDB or MySQL database schema name
            PHOTOPRISM_DATABASE_USER: "photoprism" # MariaDB or MySQL database user name
            PHOTOPRISM_DATABASE_PASSWORD: ${MINIO_ROOT_PASSWORD} # MariaDB or MySQL database user password
            PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
            PHOTOPRISM_SITE_DESCRIPTION: "" # meta site description
            PHOTOPRISM_SITE_AUTHOR: "" # meta site author
        working_dir: "/photoprism" # do not change or remove
        volumes:
            - "~/Pictures:/photoprism/originals" # Original media files (DO NOT REMOVE)
            - "./storage:/photoprism/storage" # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
    mariadb:
        container_name: hl-photoprism-mariadb
        restart: unless-stopped
        image: mariadb:10.10
        security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
            - seccomp:unconfined
            - apparmor:unconfined
        command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
        volumes:
            - "./database:/var/lib/mysql" # DO NOT REMOVE
        environment:
            MARIADB_AUTO_UPGRADE: "1"
            MARIADB_INITDB_SKIP_TZINFO: "1"
            MARIADB_DATABASE: "photoprism"
            MARIADB_USER: "photoprism"
            MARIADB_PASSWORD: ${MINIO_ROOT_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    minio:
        container_name: hl-minio-storage
        image: docker.io/bitnami/minio:2023
        environment:
            CONSOLE_SECURE_TLS_REDIRECT: "off"
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
            MINIO_BROWSER_REDIRECT_URL: "https://minio.alemax.site"
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - miniodata:/data
    watchtower:
        restart: unless-stopped
        image: containrrr/watchtower
        profiles: ["update"]
        environment:
            WATCHTOWER_CLEANUP: "true"
            WATCHTOWER_POLL_INTERVAL: 7200 # checks for updates every two hours
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "~/.docker/config.json:/config.json" # optional, for authentication if you have a Docker Hub account
    nginx:
        container_name: hl-nginx-proxy-server
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/log.conf:/etc/nginx/log.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d/:/etc/nginx/conf.d/
            - /etc/letsencrypt/live/alemax.site/fullchain.pem:/etc/nginx/fullchain.pem
            - /etc/letsencrypt/live/alemax.site/privkey.pem:/etc/nginx/privkey.pem

volumes:
    miniodata:
