version: "3"

services:
    nginx:
        image: nginx:latest
        container_name: proxy-server
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/log.conf:/etc/nginx/log.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d/:/etc/nginx/conf.d/
            - /etc/letsencrypt/live/alemax.site/fullchain.pem:/etc/nginx/fullchain.pem
            - /etc/letsencrypt/live/alemax.site/privkey.pem:/etc/nginx/privkey.pem
