version: "3"

services:
    minio:
        image: docker.io/bitnami/minio:2023
        environment:
          MINIO_ROOT_USER: ${MINIO_ROOT_USER}
          MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - miniodata:/data
    nginx:
        image: nginx:latest
        container_name: proxy-server
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/log.conf:/etc/nginx/log.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d/:/etc/nginx/conf.d/
            - /etc/letsencrypt/live/alemax.site:/etc/nginx
volumes:
  miniodata:
